// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYc4xcv_IavAcbzvytVj1Q04L2aZMQaNE',
    appId: '1:192100257771:web:883e2f66881d9fa50d13ae',
    messagingSenderId: '192100257771',
    projectId: 'customer-service-2e6b4',
    authDomain: 'customer-service-2e6b4.firebaseapp.com',
    storageBucket: 'customer-service-2e6b4.firebasestorage.app',
    measurementId: 'G-3VTNEVSDK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_M2F72CQh6iPQRI196-KyB6p4OUPpWU',
    appId: '1:192100257771:android:5f357b14f37565350d13ae',
    messagingSenderId: '192100257771',
    projectId: 'customer-service-2e6b4',
    storageBucket: 'customer-service-2e6b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQiPc0qVLqZvhfiINTqNWXSK7QP-BOd4',
    appId: '1:192100257771:ios:f64974de2f6499eb0d13ae',
    messagingSenderId: '192100257771',
    projectId: 'customer-service-2e6b4',
    storageBucket: 'customer-service-2e6b4.firebasestorage.app',
    iosBundleId: 'com.example.customerService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOQiPc0qVLqZvhfiINTqNWXSK7QP-BOd4',
    appId: '1:192100257771:ios:f64974de2f6499eb0d13ae',
    messagingSenderId: '192100257771',
    projectId: 'customer-service-2e6b4',
    storageBucket: 'customer-service-2e6b4.firebasestorage.app',
    iosBundleId: 'com.example.customerService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYc4xcv_IavAcbzvytVj1Q04L2aZMQaNE',
    appId: '1:192100257771:web:fe081f66937d68cf0d13ae',
    messagingSenderId: '192100257771',
    projectId: 'customer-service-2e6b4',
    authDomain: 'customer-service-2e6b4.firebaseapp.com',
    storageBucket: 'customer-service-2e6b4.firebasestorage.app',
    measurementId: 'G-1BQ875ZL0M',
  );
}
